### ISSUE TITLE
Missing packages warning on Visual Code

### ISSUE THREAD

**Issue by augustogoncalves** [apprentice3d/forge.learning#4]
I'm getting these errors when preparing my project, I guess is because still missing the `go get` command. Worth mentioning that is this expected, spent some time repeating copy&pasting :-) 

![image](https://user-images.githubusercontent.com/4291593/37460722-d5b4febc-282a-11e8-9378-f4fdcc54c63a.png)

**Comment by apprentice3d** [comment]
Yes, I think that I better add the `go get ` part when setting up the project or maybe when writing the `server.go` file

**Comment by augustogoncalves** [comment]
good idea, better

**Comment by apprentice3d** [comment]
Fixed: https://github.com/apprentice3d/forge.learning/commit/e0b43740db2d09b4de91635acc4237baf504f9da
