### ISSUE TITLE
Install Visual Code tools?

### ISSUE THREAD

**Issue by augustogoncalves** [apprentice3d/forge.learning#5]
Should I install it? If not, please add a note. If yes, maybe explain why and what's for.

![screen shot 2018-03-15 at 08 19 51](https://user-images.githubusercontent.com/4291593/37460823-2ea27c98-282b-11e8-9d60-bc1d03367065.png)

**Comment by apprentice3d** [comment]
Got it. These are for code suggestions, hover documentation, etc.
I will add a mention on that.

**Comment by apprentice3d** [comment]
Fixed: https://github.com/apprentice3d/forge.learning/commit/e0b43740db2d09b4de91635acc4237baf504f9da
