### ISSUE TITLE
Missing instructions on how to set key & secret

### ISSUE THREAD

**Issue by augustogoncalves** [apprentice3d/forge.learning#6]
For reference, see [NodeJS](http://localhost:3000/#/environment/setup/nodejs?id=launchjson) & [.NET](http://localhost:3000/#/environment/setup/net?id=webconfig)

![image](https://user-images.githubusercontent.com/4291593/37460976-a8647734-282b-11e8-9213-db3cb769facd.png)

**Comment by apprentice3d** [comment]
Ok, I will add this part into running and debugging instructions.

**Comment by augustogoncalves** [comment]
preferably, to keep consistency, include it under **Create a server** section (see references mentioned above)

**Comment by apprentice3d** [comment]
Fixed: https://github.com/apprentice3d/forge.learning/commit/92b80becd1c863c7f380dea0f944046dacec597a
