### ISSUE TITLE
F5 debug doesn't work

### ISSUE THREAD

**Issue by augustogoncalves** [apprentice3d/forge.learning#7]
`F5` debug on Visual result in this error:

![image](https://user-images.githubusercontent.com/4291593/37462434-af853c1a-2830-11e8-86ee-05b37b96fa04.png)

**Comment by augustogoncalves** [comment]
interesting, if I select the `main.go` file and press `F5`, then a different message appears... 

![image](https://user-images.githubusercontent.com/4291593/37463135-0c922b14-2833-11e8-8b51-052f3c7988f4.png)

**Comment by apprentice3d** [comment]
In running and debugging part there is an instruction bellow the image mentioning what to do.em

**Comment by augustogoncalves** [comment]
ok, that fixes the `non-main` issue, but still the `lldb-server` error...

**Comment by apprentice3d** [comment]
Never got that, I tried on a clean Windows virtual machine , but I will search for this problem. Since it is `lldb` related, I guess it is OSX specific problem.

**Comment by augustogoncalves** [comment]
For Mac OSx
1. Open a new Terminal (do not use Visual Code Integrated Terminal)
2. Run xcode-select --install
3. When prompted, click on Install

![screen shot 2018-03-15 at 09 51 14](https://user-images.githubusercontent.com/4291593/37464491-4a4d91ec-2837-11e8-8b0a-0fb47b5516fd.png)

**Comment by apprentice3d** [comment]
Fixed: https://github.com/apprentice3d/forge.learning/commit/1fdca823bff7c222abb5ba04a638e60552e3e0f2
